"""usersテーブルを追加

Revision ID: db7f128a853d
Revises: 
Create Date: 2025-08-17 06:57:24.639604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7f128a853d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='ユーザーID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('password', sa.String(255), nullable=False, comment="パスワード"),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="生年月日"),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
